# Generated by Django 3.2.16 on 2022-12-02 18:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('headline', models.CharField(blank=True, max_length=200, null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('task', models.TextField(blank=True, null=True)),
                ('actions', models.TextField(blank=True, null=True)),
                ('problems', models.TextField(blank=True, null=True)),
                ('knowledge_gained', models.TextField(blank=True, null=True)),
                ('image1', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image1')),
                ('image2', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image2')),
                ('image3', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image3')),
                ('html', models.BooleanField(default=False)),
                ('css', models.BooleanField(default=False)),
                ('javascript', models.BooleanField(default=False)),
                ('python', models.BooleanField(default=False)),
                ('flask', models.BooleanField(default=False)),
                ('react', models.BooleanField(default=False)),
                ('django', models.BooleanField(default=False)),
                ('bootstrap', models.BooleanField(default=False)),
                ('java', models.BooleanField(default=False)),
                ('sql', models.BooleanField(default=False)),
                ('jquery', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
        ),
    ]
