# Generated by Django 3.2.16 on 2022-12-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='langauage_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
