# Generated by Django 3.2.16 on 2022-12-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_langauage_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='langauage_summary',
            new_name='language_summary',
        ),
    ]
