# Generated by Django 3.2.16 on 2022-12-05 11:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20221205_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image1'),
        ),
    ]
