# Generated by Django 3.2.16 on 2022-12-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20221205_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image6_url',
        ),
        migrations.AddField(
            model_name='project',
            name='image1_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image2_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image3_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image4_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image5_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
