# Generated by Django 3.2.16 on 2022-12-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20221205_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image1_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image2_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image3_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image4_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image5_url',
        ),
    ]
