# Generated by Django 3.2.16 on 2022-12-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20221205_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_pages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='heroku',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='stripe',
            field=models.BooleanField(default=False),
        ),
    ]
