# Generated by Django 3.2.16 on 2022-12-05 16:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_image', cloudinary.models.CloudinaryField(blank=True, default='noface', max_length=255, null=True, verbose_name='user_image')),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=1054, null=True)),
                ('github_repo', models.URLField(blank=True, max_length=1054, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
