# Generated by Django 3.2.16 on 2022-12-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True, max_length=1054, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter',
            field=models.URLField(blank=True, max_length=1054, null=True),
        ),
    ]
