# Generated by Django 3.2.16 on 2022-12-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20221206_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_updated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
